Repository scalecube/scalecube-organization-service, pull requests merged in 2019-02, with the labels that each got.

#88 Fix `workdir` in Dockerfile
  scalecube-organization/Dockerfile
Labels: ready for review

#89 Add API to retrieve public key
  scalecube-organization-api/src/main/java/io/scalecube/account/api/OrganizationService.java
  scalecube-organization-api/src/main/java/io/scalecube/account/api/PublicKey.java
  scalecube-organization/pom.xml
Labels: enhancement, ready for review

#91 Fix typo `.onError`
  scalecube-organization/src/main/java/io/scalecube/organization/OrganizationServiceImpl.java
Labels: ready for review

#87 mpa-7603 api keys and organization management
  ApiDocs/addOrganizationApiKey.apidoc
  ApiDocs/getUserOrganizationsMembership.apidoc
  ApiDocs/overview.apidoc
  scalecube-organization/src/test/resources/features/mpa-7603-Organization-service-UT-Add-Api-Key
  scalecube-organization/src/test/resources/features/mpa-7603-Organization-service-UT-Delete-Api-Key
  scalecube-organization/src/test/resources/features/mpa-7603-Organization-service-UT-Get-Organization
  scalecube-organization/src/test/resources/features/mpa-7603-Organization-service-UT-Leave-Organization
  scalecube-organization/src/test/resources/features/mpa-7603-Organization-service-UT-Update-Organization
Labels: Feature file, ready for review

#81 Mpa 7657 organization service UT: create&delete
  ApiDocs/createOrganization.apidoc
  scalecube-organization/src/test/resources/features/mpa-7657-Create-organization.feature
  scalecube-organization/src/test/resources/features/mpa-7657-Delete-organization.feature
Labels: Feature file, ready for review

#85 Mpa 7679 org service UT for members management
  API-Calls-examples.json
  ApiDocs/getOrganization.apidoc
  ApiDocs/getUserOrganizationsMembership.apidoc
  ApiDocs/inviteMember.apidoc
  ApiDocs/updateOrganizationMemberRole.apidoc
  scalecube-organization/src/test/java/resources/features/mpa-7229-Configuration-service-auto-tests-part-2-Organization-service.feature
  scalecube-organization/src/test/resources/features/mpa-7679-Organization-service-UT-Get-Member
  scalecube-organization/src/test/resources/features/mpa-7679-Organization-service-UT-Get-Users-Membership
  scalecube-organization/src/test/resources/features/mpa-7679-Organization-service-UT-Invite-Member
  scalecube-organization/src/test/resources/features/mpa-7679-Organization-service-UT-Kick-out-Member
  scalecube-organization/src/test/resources/features/mpa-7679-Organization-service-UT-Update-Member-Role
Labels: Feature file, ready for review

#93 Revert changes in `CreateOrganizationRequest` (add email)
  scalecube-organization-api/src/main/java/io/scalecube/account/api/CreateOrganizationRequest.java
  scalecube-organization/src/main/java/io/scalecube/organization/opearation/CreateOrganization.java
  scalecube-organization/src/test/java/io/scalecube/organization/Base.java
  scalecube-organization/src/test/java/io/scalecube/organization/CreateOrganizationTest.java
Labels: ready for review

#97 Develop tc s numb update
  scalecube-organization/src/test/resources/features/mpa-7603-Organization-service-UT-Add-Api-Key
  scalecube-organization/src/test/resources/features/mpa-7603-Organization-service-UT-Delete-Api-Key
  scalecube-organization/src/test/resources/features/mpa-7603-Organization-service-UT-Get-Organization
  scalecube-organization/src/test/resources/features/mpa-7603-Organization-service-UT-Leave-Organization
  scalecube-organization/src/test/resources/features/mpa-7603-Organization-service-UT-Update-Organization
  scalecube-organization/src/test/resources/features/mpa-7657-Delete-organization.feature
  scalecube-organization/src/test/resources/features/mpa-7679-Organization-service-UT-Get-Member
  scalecube-organization/src/test/resources/features/mpa-7679-Organization-service-UT-Get-Users-Membership
  scalecube-organization/src/test/resources/features/mpa-7679-Organization-service-UT-Invite-Member
  scalecube-organization/src/test/resources/features/mpa-7679-Organization-service-UT-Kick-out-Member
  scalecube-organization/src/test/resources/features/mpa-7679-Organization-service-UT-Update-Member-Role
Labels: enhancement

#98 Rename feature files
  scalecube-organization/src/test/resources/features/mpa-7229-Configuration-service-auto-tests-part-2-Organization-service.feature
  scalecube-organization/src/test/resources/features/mpa-7603-Organization-service-Add-Api-Key.feature
  scalecube-organization/src/test/resources/features/mpa-7603-Organization-service-Delete-Api-Key.feature
  scalecube-organization/src/test/resources/features/mpa-7603-Organization-service-Get-Organization.feature
  scalecube-organization/src/test/resources/features/mpa-7603-Organization-service-Leave-Organization.feature
  scalecube-organization/src/test/resources/features/mpa-7603-Organization-service-Update-Organization.feature
  scalecube-organization/src/test/resources/features/mpa-7679-Organization-service-Get-Member.feature
  scalecube-organization/src/test/resources/features/mpa-7679-Organization-service-Get-Users-Membership.feature
  scalecube-organization/src/test/resources/features/mpa-7679-Organization-service-Invite-Member.feature
  scalecube-organization/src/test/resources/features/mpa-7679-Organization-service-Kick-out-Member.feature
  scalecube-organization/src/test/resources/features/mpa-7679-Organization-service-Update-Member-Role.feature
Labels: ready for review

#101 Mp 7652
  scalecube-organization/src/test/java/io/scalecube/organization/CreateOrganizationIntegrationTest.java
  scalecube-organization/src/test/java/io/scalecube/organization/DeleteOrganizationIntegrationTest.java
Labels: ready for review

#100 mpa-7603/ Implemented filter by role priority in responses
  scalecube-organization-api/src/main/java/io/scalecube/account/api/Role.java
  scalecube-organization/src/main/java/io/scalecube/organization/opearation/AddOrganizationApiKey.java
  scalecube-organization/src/main/java/io/scalecube/organization/opearation/DeleteOrganizationApiKey.java
  scalecube-organization/src/main/java/io/scalecube/organization/opearation/GetOrganization.java
  scalecube-organization/src/main/java/io/scalecube/organization/opearation/ServiceOperation.java
  scalecube-organization/src/main/java/io/scalecube/organization/opearation/UpdateOrganization.java
  scalecube-organization/src/test/java/io/scalecube/organization/it/AddOrganizationApiKeyIntegrationTest.java
  scalecube-organization/src/test/java/io/scalecube/organization/it/DeleteOrganizationApiKeyIntegrationTest.java
  scalecube-organization/src/test/java/io/scalecube/organization/it/GetOrganizationIntegrationTest.java
  scalecube-organization/src/test/java/io/scalecube/organization/it/UpdateOrganizationIntegrationTest.java
Labels: ready for review

#103 Fixed getting user organization membership
  scalecube-organization/src/main/java/io/scalecube/organization/operation/GetUserOrganizationsMembership.java
  scalecube-organization/src/main/java/io/scalecube/organization/operation/ServiceOperation.java
  scalecube-organization/src/main/java/io/scalecube/organization/repository/exception/EntityNotFoundException.java
  scalecube-organization/src/test/java/io/scalecube/organization/it/GetUserMembershipTest.java
Labels: ready for review
