Repository scalecube/scalecube-organization-service, pull requests merged in 2019-01, with the labels that each got.

#60 Develop api doc organization service
  API-Calls-examples.json
  ApiDocs/_apidoc.js
  ApiDocs/addOrganizationApiKey.apidoc
  ApiDocs/apidoc-template.json
  ApiDocs/apidoc.json
  ApiDocs/common.apidoc
  ApiDocs/createOrganization.apidoc
  ApiDocs/datatypes.apidoc
  ApiDocs/deleteOrganization.apidoc
  ApiDocs/deleteOrganizationApiKey.apidoc
  ApiDocs/getOrganization.apidoc
  ApiDocs/getOrganizationMembers.apidoc
  ApiDocs/getUserOrganizationsMembership.apidoc
  ApiDocs/inviteMember.apidoc
  ApiDocs/kickoutMember.apidoc
  ApiDocs/leaveOrganization.apidoc
  ApiDocs/overview.apidoc
  ApiDocs/updateOrganization.apidoc
  ApiDocs/updateOrganizationMemberRole.apidoc
  src/main/scripts/cd/release-generate-docs.sh
Labels: enhancement

#72 Fix bug with calculation of token expiration time
  scalecube-organization/src/main/java/io/scalecube/jwt/WebToken.java
  scalecube-organization/src/main/java/io/scalecube/tokens/JwtApiKey.java
  scalecube-organization/src/main/java/io/scalecube/tokens/store/ApiKeyBuilder.java
  scalecube-organization/src/main/resources/app.config.properties
Labels: bug, ready for review

#68 Refactoring of configuration mechanism
  scalecube-organization/src/main/java/io/scalecube/config/AppConfiguration.java
  scalecube-organization/src/main/java/io/scalecube/config/AppConfigurationException.java
  scalecube-organization/src/main/java/io/scalecube/config/ConfigRegistryConfiguration.java
  scalecube-organization/src/main/java/io/scalecube/jwt/WebToken.java
  scalecube-organization/src/main/java/io/scalecube/organization/repository/couchbase/CouchbaseEntityRepository.java
  scalecube-organization/src/main/java/io/scalecube/organization/repository/couchbase/CouchbaseOrganizationMembersRepositoryAdmin.java
  scalecube-organization/src/main/java/io/scalecube/organization/repository/couchbase/CouchbaseOrganizationRepository.java
  scalecube-organization/src/main/java/io/scalecube/organization/repository/couchbase/CouchbaseProperties.java
  scalecube-organization/src/main/java/io/scalecube/organization/repository/couchbase/CouchbaseRepositoryFactory.java
  scalecube-organization/src/main/java/io/scalecube/organization/repository/couchbase/CouchbaseSettings.java
  scalecube-organization/src/main/java/io/scalecube/organization/repository/couchbase/CouchbaseUserOrganizationMembershipRepository.java
  scalecube-organization/src/main/java/io/scalecube/organization/repository/couchbase/admin/InsertBucketOperation.java
  scalecube-organization/src/main/java/io/scalecube/organization/repository/couchbase/admin/InsertUserOperation.java
  scalecube-organization/src/main/java/io/scalecube/server/DiscoveryOptions.java
  scalecube-organization/src/main/java/io/scalecube/server/OrganizationServiceRunner.java
  scalecube-organization/src/main/java/io/scalecube/tokens/JwtApiKey.java
  scalecube-organization/src/main/java/io/scalecube/tokens/PublicKeyProviderFactory.java
  scalecube-organization/src/main/java/io/scalecube/tokens/store/ApiKeyBuilder.java
  scalecube-organization/src/main/java/io/scalecube/tokens/store/VaultKeyStore.java
  scalecube-organization/src/main/java/io/scalecube/tokens/store/VaultPathBuilder.java
  scalecube-organization/src/main/resources/app.config.properties
  scalecube-organization/src/main/resources/couchbase-settings.properties
  scalecube-organization/src/main/resources/couchbase.config.properties
  scalecube-organization/src/main/resources/discovery.config.properties
  scalecube-organization/src/main/resources/settings.properties
Labels: enhancement, ready for review

#58 Clean up `pom.xml` and `Dockerfile`
  pom.xml
  scalecube-organization-api/pom.xml
  scalecube-organization/Dockerfile
  scalecube-organization/pom.xml
Labels: ready for review

#82 Api doc update
  ApiDocs/_apidoc.js
  ApiDocs/addOrganizationApiKey.apidoc
  ApiDocs/apidoc-template.json
  ApiDocs/apidoc.json
  ApiDocs/createOrganization.apidoc
  ApiDocs/datatypes.apidoc
  ApiDocs/deleteOrganization.apidoc
  ApiDocs/deleteOrganizationApiKey.apidoc
  ApiDocs/getOrganization.apidoc
  ApiDocs/getOrganizationMembers.apidoc
  ApiDocs/getUserOrganizationsMembership.apidoc
  ApiDocs/inviteMember.apidoc
  ApiDocs/kickoutMember.apidoc
  ApiDocs/leaveOrganization.apidoc
  ApiDocs/overview.apidoc
  ApiDocs/updateOrganization.apidoc
  ApiDocs/updateOrganizationMemberRole.apidoc
Labels: enhancement, ready for review

#83 API doc update
  ApiDocs/addOrganizationApiKey.apidoc
  ApiDocs/apidoc-template.json
  ApiDocs/apidoc.json
  ApiDocs/createOrganization.apidoc
  ApiDocs/datatypes.apidoc
  ApiDocs/deleteOrganization.apidoc
  ApiDocs/deleteOrganizationApiKey.apidoc
  ApiDocs/getOrganization.apidoc
  ApiDocs/getOrganizationMembers.apidoc
  ApiDocs/getUserOrganizationsMembership.apidoc
  ApiDocs/inviteMember.apidoc
  ApiDocs/kickoutMember.apidoc
  ApiDocs/leaveOrganization.apidoc
  ApiDocs/overview.apidoc
  ApiDocs/updateOrganization.apidoc
  ApiDocs/updateOrganizationMemberRole.apidoc
  src/main/scripts/cd/deploy.sh
  src/main/scripts/cd/release.sh
Labels: enhancement
